import type { NextPage } from 'next';
import { signIn, signOut } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '@/utils/trpc';

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(['billGroup.getmygroups']);
  console.log(data, isLoading);

  const { mutate } = trpc.useMutation('billGroup.create');

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => signIn()}>Sign In</button>
      <button onClick={() => signOut()}>Log out</button>
      <button onClick={() => mutate({ name: 'My first group' })}>Add new</button>
    </>
  );
};

export default Home;
